name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: pnpm install && pnpm build

    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.TG_HOST }}
        user: ${{ secrets.TG_USER }}
        pass: ${{ secrets.TG_PASS }}
        connect_timeout: 10s
        local: './dist/*'
        remote: /home/ubuntu/niniix/cssanimation/
    